# Changes here will be overwritten by Copier
_commit: v2.0.4
_src_path: gh:lincc-frameworks/python-project-template
author_email: romain.lhoussaine@gmail.com
author_name: Romain Lhoussaine
create_example_module: false
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
- pylint
- black
- isort
failure_notification: []
include_benchmarks: false
include_docs: false
mypy_type_checking: basic
package_name: aoc
project_license: MIT
project_name: advent_of_code2024
project_organization: Personnal
python_versions:
- '3.13'
